FROM node:14-alpine

# Copy entrypoint
COPY ./docker/entrypoint.sh /entrypoint.sh

# Set workdir
WORKDIR /app

# Make entrypoint executable
RUN chmod +x /entrypoint.sh

EXPOSE 4200

# Set entrypoint
ENTRYPOINT /entrypoint.sh
